#pragma once

#include "ast/ast.h"
#include "ast/ast_type.h"
#include "ast/bin_ast.h"
#include "ast/body_ast.h"
#include "ast/call_ast.h"
#include "ast/func_ast.h"
#include "ast/func_decl_ast.h"
#include "ast/if_ast.h"
#include "ast/let_ast.h"
#include "ast/loop_ast.h"
#include "ast/num_ast.h"
#include "ast/ret_ast.h"
#include "ast/stmt_ast.h"
#include "ast/ty_ast.h"
#include "ast/var_ast.h"
#include "ast/while_ast.h"
